#!/usr/bin/env php
<?php

require __DIR__.'/../vendor/autoload.php';

use Bound1ess\MermaidPhp\Graph,
	Bound1ess\MermaidPhp\Printer,
	Bound1ess\MermaidPhp\Node,
	Bound1ess\MermaidPhp\Link;

# ========================================================================

$graph = new Graph('from left to right');

$graph->addNodes(
	new Node('A', ['Hard edge']),
	new Node('B', ['Round edge', Node::ROUND_EDGES]),
	new Node('C', ['Decision', Node::RHOMBUS]),
	new Node('D', ['Result one']),
	new Node('E', ['Result two'])
);

$aToB = new Link($a, $b); $aToB->isOpen(false); $aToB->setText('Link text');
$bToC = new Link($b, $c); $bToC->isOpen(false);
$cToD = new Link($c, $d); $cToD->isOpen(false); $cToD->setText('One');
$cToE = new Link($c, $e); $cToE->isOpen(false); $cToE->setText('Two');

$graph->addLinks($aToB, $bToC, $cToD, $cToE);

# ========================================================================

$template = file_get_contents(__DIR__.'/template.html');

file_put_contents(
	__DIR__.'/../example.html',
	str_replace('__GRAPH__', (new Printer)->printGraph($graph, true), $template)
);
